### ISSUE TITLE
Validation split formula might be incorrect?

### ISSUE THREAD

**Issue by FremyCompany** [piegu/fastai-projects#5]
I was wondering whether
```
        idxs = np.random.randint(0, len(df_sample), len(df_sample))
```
should not be replaced by
```
        idxs = np.arange(len(df))
        np.random.shuffle(idxs)
```
to avoid duplicates.

Maybe that's just me, but I don't trust the current formula.

**Comment by piegu** [comment]
Hi. You're right. The first code gives duplicates.
You can also use the following one to avoid duplicates:
`idxs = np.random.choice(len(df), len(df), replace=False)`
